-- phpMyAdmin SQL Dump
-- version 5.1.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Creato il: Gen 25, 2022 alle 14:40
-- Versione del server: 10.4.21-MariaDB
-- Versione PHP: 8.0.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `hd_progetto`
--
CREATE DATABASE IF NOT EXISTS `hd_progetto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `hd_progetto`;

--
-- Dump dei dati per la tabella `articolo`
--

INSERT INTO `articolo` (`ID_Articolo`, `nome`, `descrizione`, `anteprima`, `img`, `prezzo`, `marca`, `quantità`, `venditore`, `categoria`, `tipologia`) VALUES
(1, 'RTX 3080', 'Marca:Gigabyte:\nDimensioni prodotto:‎32 x 12.9 x 5.5 cm:\nNumero modello Articolo:GV-N3080GAMING OC-10GD V2:\nClock di Memoria:‎19000 MHz:\nCoprocessore grafico:NVIDIA GeForce RTX 3080:\nGrafica Chipset Brand:‎NVIDIA:\nDescrizione scheda grafica:Dedicated:\nTipo memoria scheda grafica:GDDR6X:\nDimensioni memoria scheda grafica:10 GB:\nInterfaccia scheda grafica:‎PCI-Express x16:\nWattaggio:750 watt:\nPeso Articolo:1.36 kg\n', 'Le schede grafiche GeForce RTX 3080 offrono le prestazioni ultra che i giocatori bramano grazie ad Ampere, l\'architettura RTX di seconda generazione di NVIDIA. Sono costruite con RT Core e Tensor Core potenziati, nuovi multiprocessori di streaming e una memoria G6X superveloce, il tutto per offrirti una straordinaria esperienza di gioco.', 'rtx3080.png', 1700, 'Gigabyte', 6, 1, 2, 'NVidia'),
(2, 'RTX 3070', 'Marca:‎ASUS:\r\nProduttore:Asus:\r\nSerie:‎ASUS:\r\nColore:‎InColore:\r\nDimensioni prodotto:‎13.5 x 5.2 x 26.7 cm:\r\nNumero modello Articolo:‎90YV0FQ0-M0NA00:\r\nFattore di forma:‎Compatto:\r\nClock di Memoria:‎1755 MHz:\r\nCoprocessore grafico:NVIDIA GeForce RTX 3070:\r\nGrafica Chipset Brand:‎NVIDIA:\r\nDescrizione scheda grafica:‎Dedicated:\r\nTipo memoria scheda grafica:GDDR6:\r\nDimensioni memoria scheda grafica:‎8 GB:\r\nInterfaccia scheda grafica:‎PCI-Express x8:\r\nWattaggio:750 watt:\r\nPeso Articolo:‎1 kg', 'Le schede grafiche della gamma GeForce RTX 3070 si basano sull\'architettura NVIDIA Ampere di seconda generazione. Costruite con i core Ray Tracing e Tensor Core migliorati, nuovi multiprocessori di streaming e memoria ad alta velocità, offrono la potenza che ti serve per dominare anche nei giochi più intensi.', 'rtx3070.png', 1100, 'Asus', 6, 11, 2, 'NVidia'),
(3, 'RTX 3060', 'Marca:	‎Gigabyte:\r\nProduttore:Gigabyte:\r\nDimensioni prodotto:‎28.2 x 11.7 x 4.1 cm; 770 grammi:\r\nNumero modello Articolo:‎GV-N3060GAMING OC-12GD V2:\r\nClock di Memoria:‎15000 MHz:\r\nCoprocessore grafico‎:NVIDIA GeForce RTX 3060:\r\nGrafica Chipset Brand:‎NVIDIA:\r\nDescrizione scheda grafica:‎Dedicated:\r\nTipo memoria scheda grafica:GDDR6:\r\nDimensioni memoria scheda grafica:‎12 GB:\r\nInterfaccia scheda grafica:‎PCI-Express x16:\r\nPeso Articolo:‎770 g', 'Le GeForce RTX 3060 permettono di sfruttare i giochi più recenti con la potenza di Ampere, l\'architettura NVIDIA RTX di seconda generazione. Prestazioni incredibili con ray-tracing Core migliorati e Tensor Core, nuovi multiprocessori di streaming e memoria G6 ad alta velocità.', 'rtx3060.png', 860, 'Gigabyte', 6, 1, 2, 'NVidia'),
(4, 'RTX 2080 super', 'Marca:‎MSI: Produttore:MSI: Serie:‎GeForce RTX 2080 super: Colore:‎Nero: Dimensioni prodotto:‎10 x 10 x 10 cm: Numero modello Articolo:‎90YV0C33-M0NM00: Velocità processore:1515 MHz: Dimensioni RAM:‎8 GB: Clock di Memoria:‎1200 MHz: Coprocessore grafico:‎NVIDIA GeForce RTX 2080 super: Grafica Chipset Brand:‎NVIDIA: Descrizione scheda grafica:‎DUAL-RTX2080-8G: Tipo memoria scheda grafica:‎DDR4 SDRAM: Interfaccia scheda grafica:PCI-E: Peso Articolo:‎1.97 kg', 'La NVIDIA® GeForce® RTX 2080 SUPER™ è alimentata dall\'architettura NVIDIA Turing™ con più core, clock più elevati e memoria più veloce per le massime prestazioni e nuovi incredibili livelli di realismo. È ora di prepararsi e ottenere super poteri.', 'rtx2080super.png', 800, 'MSI', 6, 9, 2, 'NVidia'),
(5, 'RTX 2070 super', 'Marca:‎ASUS: Produttore:‎Asus: Serie:‎RTX 2070 Super: Colore:‎Nero: Dimensioni prodotto:30.5 x 13.06 x 4.89 cm: Numero modello Articolo:‎S10226254: Dimensioni RAM:‎8 GB: Clock di Memoria:‎14000 MHz: Coprocessore grafico:NVIDIA GeForce RTX 2070 super: Grafica Chipset Brand:NVIDIA: Tipo memoria scheda grafica:‎GDDR6: Dimensioni memoria scheda grafica:‎8 GB: Interfaccia scheda grafica:‎PCI-E: Wattaggio:550 watt: Peso Articolo:‎1 kg', 'NVIDIA RTX è la piattaforma più avanzata per il ray-tracing e le tecnologie IA che stanno rivoluzionando il modo in cui giochiamo e creiamo. Oltre 150 giochi e applicazioni utilizzano RTX per offrire grafica realistica con prestazioni incredibilmente veloci o nuove funzionalità IA all\'avanguardia come NVIDIA DLSS e NVIDIA Broadcast. RTX è il nuovo standard.', 'rtx2070super.png', 760, 'Asus', 6, 11, 2, 'NVidia'),
(6, 'RTX 2060 super', 'Marca:‎MSI: Produttore:‎MSI COMPUTER: Serie:‎RTX 2060 Super: Dimensioni prodotto:‎23.1 x 4.2 x 12.8 cm: Numero modello Articolo:‎912-V375-623: Dimensioni RAM:‎8 GB: Clock di Memoria:‎14000 MHz: Coprocessore grafico‎:NVIDIA GeForce RTX 2060 super: Grafica Chipset Brand:NVIDIA: Tipo memoria scheda grafica:‎GDDR6: Dimensioni memoria scheda grafica:‎6 GB: Interfaccia scheda grafica:‎PCI-E: Voltaggio:‎12 Volt: Wattaggio:‎550 watt: Peso Articolo:800 g', 'NVIDIA RTX è la piattaforma più avanzata per il ray-tracing e le tecnologie IA che stanno rivoluzionando il modo in cui giochiamo e creiamo. Oltre 150 giochi e applicazioni utilizzano RTX per offrire grafica realistica con prestazioni incredibilmente veloci o nuove funzionalità IA all\'avanguardia come NVIDIA DLSS e NVIDIA Broadcast. RTX è il nuovo standard.', 'rtx2060super.png', 700, 'MSI', 6, 9, 2, 'NVidia'),
(7, 'Radeon RX 6900 XT', 'Marca:MSI: Produttore:‎MSI COMPUTER: Serie:100822.331_2xs: Colore:‎Blu Navy: Dimensioni prodotto:‎32.4 x 14.1 x 5.5 cm: Numero modello Articolo:‎Radeon RX 6900 XT 16G: Clock di Memoria:‎16000 MHz: Coprocessore grafico:AMD Radeon RX 6900 XT: Tipo memoria scheda grafica:‎GDDR6: Dimensioni memoria scheda grafica:‎16 GB: Interfaccia scheda grafica:‎PCI-E: Voltaggio:‎230 Volt: Wattaggio:‎300 watt: Peso Articolo:2.3 kg', 'La scheda grafica AMD Radeon™ RX 6900 XT, basata sull\'architettura AMD RDNA™ 2, con 80 potenti unità di elaborazione avanzate, 128 MB di tutta la nuova AMD Infinity Cache e 16 GB di memoria GDDR6 dedicata, è progettata per offrire frame rate ultra elevati e gioco serio con risoluzione 4K.', 'rx6900.png', 1500, 'MSI', 6, 9, 2, 'AMD'),
(8, 'Radeon RX 6800 XT', 'Marca:	‎MSI: Produttore:‎MSI COMPUTER: Colore:‎Nero: Dimensioni prodotto:	34 x 13.9 x 5.7 cm: Numero modello Articolo:‎RX-68XTACBD9: Clock di Memoria:‎16 GHz: Coprocessore grafico:‎AMD RX 6800 XT: Grafica Chipset Brand:‎AMD: Tipo memoria scheda grafica:‎GDDR6: Dimensioni memoria scheda grafica:‎16 GB: Interfaccia scheda grafica:‎PCI-Express x16: Peso Articolo:‎2.42 kg', 'La scheda grafica AMD Radeon™ RX 6800 XT, basata sull\'architettura AMD RDNA™ 2, con 72 potenti unità di elaborazione avanzate, 128 MB di tutta la nuova AMD Infinity Cache e 16 GB di memoria GDDR6 dedicata, è progettata per offrire frame rate ultra elevati e gioco serio con risoluzione 4K', 'rx6800.png', 1300, 'MSI', 6, 9, 2, 'AMD'),
(9, 'Radeon RX 6700 XT', 'Marca:Gigabyte: Produttore:‎Gigabyte: Dimensioni prodotto:‎28.1 x 11.5 x 4.9 cm: Numero modello Articolo:‎GV-R67XTGAMING OC-12GD: Clock di Memoria:‎16000 MHz: Coprocessore grafico:‎RX 6700 XT: Grafica Chipset Brand:‎AMD: Descrizione scheda grafica:‎Dedicated: Tipo memoria scheda grafica:GDDR6: Dimensioni memoria scheda grafica:‎12 GB: Interfaccia scheda grafica:‎PCI-Express x16: Peso Articolo:‎1.34 kg', 'La scheda grafica AMD Radeon™ RX 6700 XT, basata sull\'architettura AMD RDNA™ 2, con 40 potenti unità di elaborazione avanzate, la nuovissima AMD Infinity Cache e 12 GB di memoria GDDR6 dedicata, è progettata per offrire frame rate ultra elevati e potenza Gioco con risoluzione 1440p.', 'rx6700.png', 900, 'Gigabyte', 6, 1, 2, 'AMD'),
(10, 'Radeon RX 6600 XT', 'Marca:‎ASUS: Produttore:‎Asus: Serie:‎DUAL-RX6600XT-O8G: Colore:Nero: Dimensioni prodotto:24.3 x 13.4 x 4.9 cm: Numero modello Articolo:‎90YV0GN1-M0NA00: Coprocessore grafico:‎AMD Radeon RX 6600 XT: Grafica Chipset Brand:‎AMD: Descrizione scheda grafica:‎Dedicata: Tipo memoria scheda grafica:‎GDDR6: Dimensioni memoria scheda grafica:‎8 GB: Interfaccia scheda grafica:‎PCI-E: Peso Articolo:‎1 kg', 'Presentazione della scheda grafica AMDRadeon™ RX 6600 XT, dotata dell\'innovativa architettura AMD RDNA™ 2, progettata per offrire la migliore esperienza di gioco a 1080p.', 'rx6600.png', 650, 'Asus', 6, 11, 2, 'AMD'),
(11, 'Radeon RX 5700 XT', 'Marca:Gigabyte: Produttore:Gigabyte: Dimensioni prodotto:‎32.5 x 3 x 1.4 cm: Numero modello Articolo:‎320750: Coprocessore grafico:‎FirePro V4900: Tipo memoria scheda grafica:‎GDDR4: Interfaccia uscita video:DisplayPort, HDMI: Velocità di clock GPU:1885 MHz: Dimensioni memoria scheda grafica:‎8 GB: Interfaccia scheda grafica:PCI-E: Peso Articolo:1 kg', 'Le grandi esperienze di gioco si creano piegando le regole. La nuovissima Radeon RX 5700 XT alimentata da RDNA per prestazioni eccezionali e giochi ad alta fedeltà. Prendi il controllo con la Radeon RX 5700 XT e sperimenta un gioco potente e accelerato personalizzato per te.', 'rx5700.png', 900, 'Gigabyte', 6, 1, 2, 'AMD'),
(12, 'Radeon RX 5600 XT', 'Marca:‎Asus: Produttore:‎Asus: Dimensioni prodotto:‎30 x 20 x 10 cm: Numero modello Articolo:‎11296-01-20G: Clock di Memoria:‎1750 MHz: Coprocessore grafico:‎AMD Radeon RX 570: Grafica Chipset Brand:‎AMD: Tipo memoria scheda grafica:‎GDDR6: Dimensioni memoria scheda grafica:‎6 GB: Interfaccia scheda grafica:‎PCI-Express x16: Wattaggio:‎160 watt: Peso Articolo:‎0.96 kg', 'La nuovissima Radeon RX 5600 XT alimentata da RDNA offre le massime prestazioni di gioco a 1080p. Sperimenta giochi altamente coinvolgenti, altamente personalizzabili e ad alta fedeltà. Gioca al meglio con la Radeon RX 5600 XT.', 'rx5600.png', 600, 'Asus', 6, 11, 2, 'AMD'),
(13, 'VENGEANCE 2x8 3600mhz', 'Marca:‎Corsair: Produttore:‎Corsair: Serie:‎Vengeance PRO RGB DDR4-RAM 3600 MHz 2x 8GB: Colore:‎Nero: Dimensioni prodotto:‎13.82 x 0.76 x 5.08 cm: Numero modello Articolo:‎CMW16GX4M2D3600C18: Dimensioni RAM:‎16 GB: Tecnologia di memoria:	‎DDR4: Tipologia di memoria computer:‎DDR4 SDRAM: Clock di Memoria:‎3600 MHz: Voltaggio:1.35 Volt: Peso Articolo:‎120 g', 'Corsair Vengeance RGB PRO Black DDR4-RAM 3600 MHz 2x 8GB memoria', 'vengeance2x83600.png', 85, 'Corsair', 6, 4, 4, NULL),
(14, 'VENGEANCE 2x16 3600mhz', 'Marca:‎Corsair: Produttore:‎Corsair: Modello‎:CMK32GX4M2D3600C18: Nome modello:	‎Vengeance LPX: Dimensioni prodotto:‎13.49 x 0.71 x 3.35 cm: Numero modello Articolo:‎CMK32GX4M2D3600C18: Numero Articolo:‎CMK32GX4M2D3600C18: Dimensioni RAM:‎32 GB: Tecnologia memoria RAM:‎DDR4: Tipologia di memoria computer:‎DDR4 SDRAM: Voltaggio:‎1.35 Volt: Peso Articolo:‎77.1 g', 'Corsair Vengeance LPX DDR4-RAM 3600 MHz 2x 16GB memoria, Nero', 'vengeance2x163600.png', 140, 'Corsair', 6, 4, 4, NULL),
(15, 'Ballistix 2x8 3200mhz', 'Marca:‎Crucial: Produttore:‎Crucial: Colore‎:Bianco: Dimensioni prodotto:13.33 x 0.72 x 3.92 cm: Numero modello Articolo:‎BL2K8G32C16U4W: Dimensioni RAM:‎16 GB: Tecnologia di memoria‎:DDR4: Tipologia di memoria computer:‎DDR4 SDRAM: Clock di Memoria:‎3200 MHz: Voltaggio‎:1.35 Volt: Wattaggio:‎15: Peso Articolo:‎9.98 g', 'Crucial Ballistix BL2K8G32C16U4W 3200 MHz, DDR4, DRAM, Memoria Gaming Kit per Computer Fissi, 16GB (8GB x2), CL16, Bianco', 'ballistix2x83200.png', 80, 'Crucial', 6, 5, 4, NULL),
(16, 'Ballistix 2x8 3600mhz', 'Marca:‎Crucial: Produttore:‎Crucial: Colore:‎Nero: Dimensioni prodotto:13.33 x 0.72 x 3.92 cm: Numero modello Articolo:‎BL2K8G36C16U4B: Dimensioni RAM:‎16 GB: Tecnologia di memoria:	‎DDR4: Tipologia di memoria computer	‎:DDR4 SDRAM: Clock di Memoria:3600 MHz: Voltaggio:‎1.35 Volt: Wattaggio:‎15: Peso Articolo:‎113 g', 'Crucial Ballistix BL2K8G36C16U4B 3600 MHz, DDR4, DRAM, Memoria Gaming Kit per Computer Fissi, 16GB (8GB x2), CL16, Nero', 'ballistix2x83600.png', 90, 'Crucial', 6, 5, 4, NULL),
(17, 'Core i7-11700K', 'Marca:‎Intel: Produttore:‎Intel: Dimensioni prodotto:‎22 x 17 x 10 cm: Numero modello Articolo:‎BX8070811700K: Marchio processore:‎Intel: Supporto processore:LGA 1200: Numero processori:‎8: Wattaggio:‎125 watt: Peso Articolo:70 g', 'Intel Core i7-11700K processore desktop di 11a generazione (cloack base: 3,6 GHz. Tuboost: 4,9 GHz, 8 core, LGA1200) BX8070811700 K', 'i711700k.png', 330, 'Intel', 6, 3, 5, NULL),
(18, 'Core i5-12600K', 'Marca:‎Intel: Produttore:‎Intel: Colore:‎Nero: Dimensioni prodotto:‎12 x 10 x 8 cm: Numero modello Articolo:‎BX8071512600K: Marchio processore:‎Intel: Tipo processore:‎Core i5: Velocità processore:‎4.9 GHz: Dimensioni RAM:‎128 GB: Wattaggio:‎125 watt: Peso Articolo:‎40 g', 'Intel Core i5-12600K - Processore desktop di 12a generazione (cloack base: 3,7 GHz Tuboboost: 4,9 GHz, 6 core, LGA1700, RAM DDR4 e DDR5 fino a 128 GB) BX8071512600K', 'i512600K.png', 350, 'Intel', 6, 3, 5, NULL),
(19, 'Core i9-12900K', 'Marca:Intel: Produttore:‎Intel: Colore:Trasparente: Dimensioni prodotto:‎13.5 x 14 x 16.5 cm: Numero modello Articolo:‎BX8071512900K: Marchio processore:‎Intel: Tipo processore:‎5X86: Velocità processore:‎3.2 GHz: Wattaggio:‎125 watt: Peso Articolo:‎460 g', 'Intel Core i9-12900K, 8Core+8efficentsCore/24Threads, 3.20-5.20GHz, in scatola senza Dissipatore', 'i912900K.png', 700, 'Intel', 6, 3, 5, NULL),
(20, 'Core i9-11900K', 'Marca:‎Intel: Produttore:‎Intel: Dimensioni prodotto:‎10 x 8 x 15 cm: Numero modello Articolo:‎BX8070811900K: Marchio processore:‎Intel: Tipo processore:‎Intel Core i9-11900K: Velocità processore:‎3.5 GHz: Supporto processore:‎LGA 1200: Numero processori:‎8: Wattaggio:‎125 watt: Peso Articolo:‎70 g', 'Intel Core i9-11900K - Processore (frequenza di base: 3,5 GHz Tuboboost: 5,1 GHz, 8 core, LGA1200) BX8070811900K', 'i911900K.png', 500, 'Intel', 6, 3, 5, NULL),
(21, 'Core i5-11400', 'Marca:‎Intel: Produttore:‎Intel: Dimensioni prodotto:‎70 x 10 x 12 cm: Numero modello Articolo:‎BX8070811400F: Marchio processore:‎Intel: Tipo processore:‎Intel Core i5-11400F: Velocità processore:‎2.6 GHz:  Supporto processore:‎LGA 1200: Numero processori:‎6: Wattaggio:‎65 watt: Peso Articolo:‎310 g', 'Intel Core i5-11400F - Processore desktop da 11 generazione (clock di base: 2.6 GHz Tuboost: 4.4 GHz, 6 core, LGA1200) BX8070811400F', 'i511400.png', 200, 'Intel', -2, 3, 5, NULL),
(22, 'Ryzen 5 5600X', 'Marca:AMD: Produttore:‎AMD: Dimensioni del collo:‎13.9 x 13.3 x 7.4 cm: Numero modello Articolo:‎100-100000065CBX: Marchio processore:‎AMD: Velocità processore:‎3.7 GHz: Supporto processore:‎Socket AM4: Numero processori:‎6: Wattaggio:‎65 watt: Peso Articolo:‎430 g', 'AMD AM4 Ryzen 5 6 Box 5600X 3,7GHz Max Boost 4,6GHz 6xCore 35MB 65W con Wraith Stealth Cooler', 'ryzen55600x.png', 320, 'AMD', 6, 2, 5, NULL),
(23, 'Ryzen 9 3900X', 'Marca:AMD:\nProduttore:‎AMD:\nSerie:3900X:\nColore:‎MultiColore:\nDimensioni prodotto:‎4 x 4 x 0.6 cm:\nNumero modello Articolo:‎Ryzen 9 3900X:\nMarchio processore:‎AMD:\nTipo processore:‎Ryzen 9 3900X:\nVelocità processore:‎4.6 GHz:\nSupporto processore:‎Socket AM4:\nNumero processori:12:\nWattaggio:105 watt:\nPeso Articolo:‎45.3 g', 'Processore AMD Ryzen 9 5900X (12C/24T, 70 MB di cache, fino a 4,8 GHz Max Boost)', 'ryzen93900x.png', 450, 'AMD', 6, 2, 5, NULL),
(24, 'Ryzen 9 5900X', 'Marca:‎AMD: Produttore:AMD: Serie:AMD Ryzen™ 9 5900X: Dimensioni prodotto:‎4 x 4 x 0.6 cm: Numero modello Articolo:‎AMD Ryzen 9 5900X: Marchio processore:‎AMD: Velocità processore:‎3.7 GHz: Supporto processore:‎Socket AM4: Numero processori:‎12: Wattaggio:‎105 watt: Peso Articolo:‎79.2 g', 'Processore AMD Ryzen 9 5900X (12C/24T, 70 MB di cache, fino a 4,8 GHz Max Boost)', 'ryzen95900x.png', 520, 'AMD', 6, 2, 5, NULL),
(25, 'Ryzen 3 3300X', 'Marca:‎AMD: Produttore:‎AMD: Serie:‎CPU AMD Ryzen 3 3300X AM4: Colore:‎MultiColore: Dimensioni prodotto‎:13.1 x 7.1 x 13.4 cm: Numero modello Articolo:‎100-100000159BOX: Marchio processore:‎AMD: Tipo processore:‎Ryzen 3 1300X: Velocità processore:‎3.8 GHz: Supporto processore:‎Socket AM4: Numero processori:‎4: Wattaggio:‎65 watt: Peso Articolo:‎422 g', 'AMD CPU Ryzen 3 3300X AM4, 4 core, cloack 4.3 GHz', 'ryzen33300x.png', 280, 'AMD', 6, 2, 5, NULL),
(26, 'Ryzen 7 3700X', 'Marca:AMD: Produttore:‎AMD: Serie:‎CPU AMD Ryzen 7 3700X AM4: Colore:‎MultiColore: Dimensioni prodotto:‎4 x 4 x 0.6 cm: Numero modello Articolo:‎Ryzen 7 3700X: Marchio processore:‎AMD: Tipo processore:‎AMD Ryzen 7: Velocità processore:‎3.6 GHz: Supporto processore:‎Socket AM4: Numero processori:‎8: Wattaggio:‎65 watt: Peso Articolo:‎635 g', 'AMD Ryzen 7 3700X, processore Wraith Prism per dissipatore di calore (32 MB, 8 core, velocità 4,4 GHz, 65 W)', 'ryzen73700x.png', 320, 'AMD', 6, 2, 5, NULL),
(27, 'MasterLiquid ML240L V2', 'Marca:‎Cooler Master: Produttore:‎Coolermaster: Serie:‎MasterLiquid ML240L V2 RGB White Edition: Colore:‎bianco: Dimensioni prodotto:‎15.7 x 11.96 x 2.72 cm: Numero modello Articolo:‎MLW-D24M-A18PC-RW: Wattaggio:‎2.36 watt: Peso Articolo:‎1.37 kg', 'V2 RGB silenziosamente aggiornato: illuminazione RGB più brillante, raffreddamento migliorato e prestazioni significativamente più silenziose per ML240L RGB versione 2. Lo scambiatore di calore a piastre in rame è l\'ancora della pompa di 3a generazione. Pompa a doppia camera con maggior capacità di acqua e migliore flusso tra camere.', 'masterliquidML240LV2.png', 65, 'Cooler Master', 6, 6, 7, NULL),
(28, 'MasterLiquid ML360', 'Marca:‎Cooler Master: Produttore:‎Coolermaster: Serie: ‎MasterLiquid ML360 Illusion: Colore:‎Nero: Numero modello Articolo:‎MLX-D36M-A18P2-R1: Wattaggio:‎2.36 watt: Peso Articolo:‎1.83 kg', 'Effetti luce straordinari sia dall\'alloggiamento della pompa traslucido 12 LED ARGB che dalle due ventole Halo 24 LED ARGB; Totalmente personalizzabile via software MasterPlus+ o controller RGB Indirizzabile Gen 2 incluso. Il nuovo design della pompa a doppia camera presenta girante interna e alloggiamento migliorati per volume maggiore e flusso d\'acqua tra camere migliorato per prestazioni e dissipazione del calore migliorate.', 'masterliquidML360.png', 130, 'Cooler Master', 6, 6, 7, NULL),
(29, 'MasterLiquid 240', 'Marca:‎Cooler Master: Produttore:‎Coolermaster: Colore:‎Nero: Dimensioni prodotto:‎14.1 x 27.2 x 32 cm: Numero modello Articolo:‎MLW-D24M-A20PW-R1: Tipo wireless:‎802.11°: Voltaggio:‎12 Volt: Peso Articolo:‎1.1 kg', 'Sistema di raffreddamento a liquido CPU silenzioso, ad alte prestazioni, in una soluzione all-in-one conveniente per principianti e costruttori esperti. Lo scambiatore di calore a piastre in rame fissa una pompa doppia, adatta sia ai kit di montaggio CPU INTEL e AMD. Discreto radiatore a bassa resistenza con 2 ventole MasterFan Pro 120 Air Balance con lame ibride, un avanzato sistema Silent Drive IC (6-30 dBA) e supporto in gomma antivibrante.', 'mastermiquid240.png', 70, 'Cooler Master', 6, 6, 7, NULL),
(30, 'NH-D15S', 'Marca‎:Noctua: Produttore:‎Noctua: Modello:‎NH-D15S CH.BK: Dimensioni prodotto	:‎16 x 15 x 13.5 cm: Numero modello Articolo:‎NH-D15S CH.BK: Numero Articolo:‎NH-D15S CH.BK: Livello di rumorosità:‎24.6 dB: Voltaggio:‎12 Volt: Wattaggio:‎1 watt: Peso Articolo:‎100 g', 'NH-D15S chromax.black è una versione a tema tutto nero del pluripremiato dissipatore silenzioso per CPU NH-D15S Noctua di qualità premium. Grazie allo stesso design asimmetrico del dissipatore a doppia torre e alla ventola NF-A15 PWM, rimane fedele alla formula di successo dell’NH-D15S, che combina eccellenti prestazioni a doppia torre con un’eccezionale compatibilità RAM, case e PCIe. Allo stesso tempo, la versione chromax.black con ventole e dissipatore di Colore nero combina queste risorse con un look elegante e discreto. ', 'nhd15s.png', 90, 'Noctua', 6, 7, 7, NULL),
(31, 'NH-D15', 'Marca:‎Noctua: Produttore:‎Noctua: Colore:‎Nero: Dimensioni prodotto‎:16.08 x 14.99 x 16.48 cm: Numero modello Articolo:‎NH-D15 CH.BK: Voltaggio:‎12 Volt: Peso Articolo:‎1.3 kg', 'NH-D15 chromax.black è una versione a tema tutto nero del modello di punta Noctua NH-D15 dei dissipatori silenziosi di qualità premium per CPU. Grazie al collaudato design del dissipatore a doppia torre e alle ventole PWM NF-A15, rimane fedele alla formula di successo di NH-D15, che gli consente di competere con le prestazioni dei radiatori ad acqua all-in-one mantenendo al contempo una silenziosità straordinaria. Allo stesso tempo, la versione chromax.black con ventole e dissipatore di Colore nero combina queste risorse con un look elegante e discreto.', 'nhd15.png', 100, 'Noctua', 6, 7, 7, NULL),
(32, 'NH-U12S', 'Marca:‎Noctua: Produttore:‎Noctua: Colore:‎Nero: Dimensioni prodotto:‎7.1 x 12.5 x 15.8 cm: Numero modello Articolo:‎NH-U12S CH.BK: Voltaggio:‎12 Volt: Peso Articolo:‎1.02 kg', 'NH-U12S chromax.black è una versione a tema tutto nero del modello di punta Noctua NH-U12S dei dissipatori silenziosi di qualità premium per CPU. Grazie allo stesso collaudato design del dissipatore a torre sottile e alla ventola NF-F12 PWM, rimane fedele alla formula di successo di NH-U12S, che combina eccellenti prestazioni di raffreddamento con un’eccezionale silenziosità di funzionamento e una straordinaria compatibilità RAM e con i case PCIe. Allo stesso tempo, la versione chromax.black con ventole e dissipatore di Colore nero combina queste risorse con un look elegante e discreto.', 'nhu12s.png', 70, 'Noctua', 6, 7, 7, NULL),
(33, 'Carbide Series SPEC-DELTA', 'Marca:‎Corsair: Produttore:‎Corsair: Colore:Nero: Dimensioni prodotto:‎43.99 x 21.01 x 45.01 cm: Numero modello Articolo:‎CC-9011166-WW: Tipo wireless:‎802.11°: Peso Articolo:‎6.35 kg', 'Lo SPEC-DELTA RGB della Serie Carbide è un case Mid-tower ATX realizzato in vetro temprato con uno stile angolare che non passa inosservato. Inoltre è dotato di un potente flusso d\'aria e di una vivace illuminazione RGB. Il pannello laterale totalmente in vetro temprato, unito al pannello anteriore trasparente fumé, mette in risalto il tuo sistema, con tre ventole RGB da 120 mm che illuminano il tuo hardware.', 'carbidespecdelta.png', 80, 'Corsair', 6, 4, 6, NULL),
(34, 'iCUE 220T RGB Airflow', 'Marca:‎Corsair: Produttore:‎Corsair: Colore:‎Nero: Dimensioni prodotto:‎39.5 x 21.01 x 45.01 cm: Numero modello Articolo:‎CC-9011173-WW: Peso Articolo:‎6.5 kg', 'Il Corsair iCUE 220T RGB Airflow è uno smart case ATX mid-tower dotato di un pannello anteriore con griglia in acciaio, che garantisce un flusso d\'aria straordinariamente elevato. Dai vita a spettacolari giochi di luce grazie alle tre ventole SP120 RGB PRO fornite in dotazione, ciascuna delle quali dotata di otto LED regolabili singolarmente e gestibili tramite il software Corsair iCUE e il Lighting Node CORE incluso.', 'icue220tRGB.png', 110, 'Corsair', 6, 4, 6, NULL),
(35, 'iCUE 5000X RGB', 'Marca:‎Corsair: Produttore:‎Corsair: Modello:‎CC-9011212-WW: Nome modello:‎ICUE 5000X RGB: Dimensioni prodotto:‎52 x 24.5 x 52 cm: Numero modello Articolo:‎CC-9011212-WW: Numero Articolo:‎CC-9011212-WW: Interfaccia Hardware:‎USB-C: Materiale:‎Vetro temperato, Lega di acciaio: Peso Articolo:‎1.5 kg', 'I quattro pannelli in vetro temperato mettono in bella mostra il tuo PC, mentre le numerose canaline con filtri antipolvere lasciano libero il passaggio per far entrare un flusso d\'aria massiccio. Con 5000X RGB, il sistema di raffreddamento diventa davvero flessibile. Include fino a dieci attacchi per ventole da 120 mm, tre ventole SP RGB ELITE con tecnologia CORSAIR AirGuide. il suo ingegnoso vano interno è stato studiato per permettere di migliorare il sistema di raffreddamento a liquido aggiungendo.', 'icue5000xRGB.png', 200, 'Corsair', 6, 4, 6, NULL),
(36, 'MasterCase H500M', 'Marca:‎Cooler Master: Produttore:‎Coolermaster: Modello:‎MCM-H500M-IHNN-S00: Nome modello:	‎H500M: Dimensioni prodotto:‎54.4 x 24.8 x 54.6 cm: Numero modello Articolo:‎MCM-H500M-IHNN-S00: Anno modello‎:2018: Livello di rumorosità:‎1 dB: Wattaggio:‎300: Numero di porte:‎5: Totale porte USB:‎5: Materiale:‎Vetro temperato: Peso Articolo:‎1 kg', 'Il pannello I/O è dotato di una porta USB 3.1 (Gen 2) Tipo C e quattro porte USB 3.0 aggiuntive. Ingresso e uscita audio con supporto per HD Audio. Il controller RGB indirizzabile incluso gestisce l\'illuminazione del sistema e può essere collegato all\'interruttore di ripristino. I pannelli laterali in vetro edge-to-edge su entrambi i lati, un pannello superiore in vetro e un pannello frontale in vetro offrono una visione chiara e completa del sistema.', 'mastercaseh500m.png', 200, 'Cooler Master', 6, 6, 6, NULL),
(37, 'MasterBox MB511', 'Marca:‎Cooler Master: Produttore:‎Coolermaster: Serie:‎MB511 ARGB: Colore:ARGB: Dimensioni prodotto:‎49.6 x 21.7 x 46.8 cm: Numero modello Articolo:‎MCB-B511D-KGNN-RGA: Numero di porte USB 3.0:‎2: Peso Articolo:‎7 kg', 'L\'illuminazione si assegna via controller o direttamente via schede madri ARGB (ASUS, Gigabyte, MSI e ASRock). I pannelli anteriore e superiore hanno filtro in rete. sette ventole da 120mm, due radiatori da 360mm su pannello superiore e anteriore assicurano che i sistemi più estremi rimangano freschi. Esibisci gli effetti di illuminazione del tuo sistema attraverso il pannello laterale in vetro temperato di 4mm di spessore.', 'masterboxmb511.png', 88, 'Cooler Master', 6, 6, 6, NULL),
(38, 'MasterBox Lite 5', 'Marca:‎Cooler Master: Produttore:‎Coolermaster: Colore:Nero: Dimensioni prodotto:‎45.45 x 20 x 46.88 cm: Numero modello Articolo:‎MCW-L5S3-KANN-01: Numero di porte USB 2.0:‎2: Peso Articolo:‎5.67 kg', 'Il case Cooler Master MasterBox Lite 5 è la prima scelta se non si vuole rinunciare a un look e alle possibilità di adattamento al proprio PC. Fai vedere la tuo build attraverso il leggero pannello laterale in acrilico e un\'elegante parte frontale in DarkMirror, ciò costituisce un fantastico modo per iniziare a personalizzare il tuo computer.', 'masterboxlite5.png', 100, 'Cooler Master', 6, 6, 6, NULL),
(39, 'RM750x', 'Marca:‎Corsair: Produttore:‎Corsair: Serie:‎Font Food Corsair RM750x 750W 80+ Bianco modulare oro: Colore:Bianco: Dimensioni prodotto:‎15 x 8.6 x 16 cm: Numero modello Articolo:CP-9020187-EU: Wattaggio:‎750 watt: Peso Articolo:1.6 kg', 'Corsair RM750x Alimentatore PC, Completamente Modulare, 80 Plus Gold, 750 Watt, EU, Serie RMX, Bianco.', 'rm700x.png', 150, 'Corsair', 6, 4, 3, NULL),
(40, 'CX450', 'Marca:Corsair: Produttore:‎Corsair: Serie:‎CX450M: Colore:‎Nero: Dimensioni prodotto:‎14 x 15 x 8.6 cm: Numero modello Articolo:‎CP-9020219-EU: Wattaggio:‎450 watt: Peso Articolo:‎1.5 kg', 'Corsair CX450M (2021) CX-M Series, 450 Watt 80 PLUS Bronze Semi-Modulare e a Bassa Rumorosità Alimentatore ATX, Connettori EPS12V Singoli, Condensatori 105 °C, Dimensioni Compatte, Nero.', 'cx450.png', 62, 'Corsair', 6, 4, 3, NULL),
(41, 'SE 530W', 'Marca:‎Thermaltake: Produttore:‎Thermaltake: Colore:‎Nero: Dimensioni prodotto:‎12.45 x 5.85 x 13.05 cm: Numero modello Articolo:‎SPS-530MPCBEU: Numero processori:‎1: Wattaggio:‎530 watt: Peso Articolo:‎1.17 kg', 'Thermaltake Smart SE 530W alimentatore modulare.', 'se530w.png', 55, 'Thermaltake', 6, 8, 3, NULL),
(42, 'BX1 RGB 750W', 'Marca:‎Thermaltake: Produttore:‎Thermaltake: Serie:‎Thermaltake Smart BX1 RGB 750W / Alimentatore per PC / PSU: Colore:Nero: Dimensioni prodotto:‎14 x 15 x 8.6 cm: Numero modello Articolo:‎PS-SPR-0650NHSABE-1: Wattaggio:‎750: Peso Articolo:‎2 kg', 'Thermaltake Smart BX1 RGB 750W Alimentatore per PC da 750 W, Nero.', 'bx1RGB750w.png', 110, 'Thermaltake', 6, 8, 3, NULL),
(43, 'v750 gold 750W', 'Marca:‎Cooler Master: Produttore:‎Coolermaster: Serie:‎V SFX Gold: Colore:‎Bianco: Dimensioni prodotto:‎10 x 12.5 x 6.35 cm: Numero modello Articolo:‎MPY-7501-SFHAGV-WE: Wattaggio:‎750 watt: Peso Articolo:‎1.42 kg', 'Cooler Master V750 SFX Gold, 750W 80 PLUS Gold, Alimentatore Full-Modular, SFF/mini-ITX, Ventola FDB Silenziosa da 92mm, Modalità Semi-Fanless, Staffa SFX-a-ATX, Garanzia di 10 Anni - 750W, bianco.', 'v750gold.png', 115, 'Cooler Master', 6, 6, 3, NULL),
(44, 'MWE 700 700W', 'Marca:‎Cooler Master: Produttore:‎Coolermaster: Serie:‎MWE White-v2: Colore:‎Bianco: Dimensioni prodotto:‎14 x 15 x 8.6 cm;: Numero modello Articolo:‎MPE-7001-ACABW-EU: Voltaggio:‎230 Volt: Wattaggio:‎700 watt: Peso Articolo:‎1.5 kg', 'Cooler Master Alimentatore MWE 700 White 230V V2, Spina UE - 80 PLUS 230V Certificato UE, Ventola 120 HDB Silenziosa, Circuito DC-to-DC + LLC con Singola Linea +12V - 3 Anni di Garanzia.', 'mwe700.png', 55, 'Cooler Master', 6, 6, 3, NULL),
(45, 'Z690 Aorus Pro', 'Marca:Gigabyte: Chipset :Intel: Colore:MultiColore: Dimensioni del collo:‎34.1 x 27.5 x 8.2 cm: Numero modello Articolo:Z690AORUSELITEDDR4: Fattore di forma:‎ATX: Supporto processore:‎LGA 1700: Tecnologia di memoria:‎DDR4: Interfaccia scheda grafica:Integrato: Tipo wireless:‎Bluetooth, 802.11a/b/g/n/ac: Peso Articolo‎:907 g', 'Regnano supreme le nuove schede madri da gioco Z690 AORUS. Il re della piattaforma di gioco continua la leggendaria linea AORUS con l\'erogazione di potenza più robusta e un design termico dominante, glorificato con la tecnologia di overclocking della memoria completa per coronare il tuo PC con le migliori prestazioni.', 'z690aorus.png', 340, 'Gigabyte', 6, 1, 1, 'Intel'),
(46, 'ROG Maximus XIII Hero', 'Marca:‎ASUS: Chipset:Intel: Serie:ROG MAXIMUS XIII HERO: Dimensioni prodotto:‎30.5 x 24.5 x 6 cm: Numero modello Articolo:‎MB ASUS ROG MAXIMUS XIII HERO: Supporto processore:‎LGA 1200: Tecnologia di memoria:	‎DDR4: Tipologia di memoria computer:‎DDR4 SDRAM: Memoria massima supportata:128 GB: Interfaccia scheda grafica:‎PCI-Express x16: Tipo wireless:‎Bluetooth, 802.11ax:                  Numero di porte HDMI:	‎1: Numero di porte Ethernet:‎2: Peso Articolo:‎1 kg', 'Caratterizzato da modifiche proprietarie al layout della traccia di memoria che migliorano l\'integrità del segnale e mitigano il rumore, Optimem III permette ai kit di memoria di funzionare a latenze più basse, tensioni ridotte e operare a frequenze più alte. Assembla ROG Maximus XIII Hero con i tuoi moduli preferiti e massimizza il throughput del processore 11ma generazione Intel Core Rocket Lake per applicazioni che richiedono un\'elevata larghezza di banda.', 'rogmaximus.png', 362, 'Asus', 6, 11, 1, 'Intel'),
(47, 'Z590 Aorus Tachyon', 'Marca:Gigabyte: Chipset:Intel: Colore:‎Cranberry: Dimensioni prodotto:‎30.5 x 24.4 x 4 cm: Numero modello Articolo:‎Z590 AORUS TACHYON: Supporto processore:‎BGA 437: Tecnologia di memoria:‎DDR: Tipologia di memoria computer	‎:DIMM: Tipo wireless:802.11ax: Peso Articolo:‎1.41 kg', 'Z590 AORUS TACHYON è l\'apice delle schede madri per l\'overclock completamente progettata da e per gli overclocker, che cercano continuamente di superare limiti di prestazioni inimmaginabili. Il suo design VRM specializzato, la traccia del layout della memoria e i pulsanti e gli interruttori di overclocking integrati consentono agli appassionati di overclocking di liberare tutto il potenziale del processore Intel Core di ultima generazione.', 'z590aorus.png', 200, 'Gigabyte', 6, 1, 1, 'Intel'),
(48, 'Z490 Taichi', 'Marca:‎Asrock: Chipset:‎Intel: Modello:‎Z490 Taichi: Dimensioni prodotto:‎34.29 x 26.67 x 7.62 cm: Anno modello:‎2020: Capacità di memoria:‎32 GB: Slot di memoria disponibili:‎4: Tecnologia memoria RAM:‎DDR4: Tipologia di memoria computer:‎DDR4 SDRAM: Numero processori:4: Supporto processore:‎LGA 1200: Interfaccia scheda grafica:‎PCI-E: Tipo wireless:‎Bluetooth: Fattore di forma:‎ATX: Peso Articolo:1.2 kg', 'Taichi rappresenta lo stato filosofico del potenziale assoluto, infinito e indifferenziato. Una scheda madre che soddisfa ogni compito, e lo fa con stile! Diventa come l\'acqua. Informe e versatile per ogni situazione.', 'z490taichi.png', 420, 'ASRock', 6, 10, 1, 'Intel'),
(49, 'X299X Designare 10G', 'Marca:‎Gigabyte: Chipset:Intel: Modello:‎X299X DESIGNARE 10G: Dimensioni prodotto:‎30.5 x 27.5 x 4 cm: Numero modello Articolo:‎X299X DESIGNARE 10G: Anno modello:‎2020: Numero Articolo:‎X299X DESIGNARE 10G: Capacità di memoria:1024 MB: Tecnologia memoria RAM:‎DDR4: Supporto processore:‎LGA 2066: Tipo di chip:‎Intel X299: Tipo wireless:‎802.11ax: Supporta tecnologia Bluetooth:	‎No: Peso Articolo:‎100 g', 'Alimentato dal controller Thunderbolt Intel il nuovo protocollo Thunderbolt 3, disponibile su due connettori USB Type-C sul retro I/O del GIGABYTE X299X DESIGNARE 10G, porta una larghezza di banda a filo singolo senza precedenti fino a 40 Gb/s - due volte più rispetto alla generazione precedente di Thunderbolt. Questo incredibile aumento della larghezza di banda è anche accompagnato dal supporto per diversi protocolli, come ad esempio DisplayPort 1.2 e USB 3.2, che è retrocompatibile con USB 3.0 e USB 2.0, aprendo un mondo di nuove possibilità.', 'x299xdesignare.png', 640, 'Gigabyte', 6, 1, 1, 'Intel'),
(50, 'ROG Strix B550-F', 'Marca:‎ASUS: Chipset:AMD: Serie:‎ROG STRIX B550-F GAMING(WI-FI): Dimensioni prodotto‎:30.5 x 24.4 x 4 cm: Numero modello Articolo:‎ROG STRIX B550-F GAMING(WI-FI): Fattore di forma:‎ATX: Supporto processore:‎Socket AM4: Dimensioni RAM:‎128 GB: Tecnologia di memoria:‎DDR4: Tipologia di memoria computer:‎DDR4 SDRAM: Memoria massima supportata:‎128 GB: Clock di Memoria:‎5000 MHz: Interfaccia scheda grafica:‎PCI-Express x16, PCI-E: Tipo wireless:Bluetooth, 802.11ax: Numero di porte USB 2.0:‎4: Numero di porte HDM	‎:1: Numero di porte Ethernet:‎1: Wattaggio:‎100: Peso Articolo:‎900 g', 'Le MB ROG Strix B550 Gaming offrono funzionalità della Serie ROG Strix X570 Gaming. Potente erogazione ed efficace raffreddamento rendono ROG Strix B550 Gaming ottime per la terza gen di CPU AMD Ryzen . Con ROG Strix B550-F Gaming (Wi-Fi) hai un vantaggio per costruire la tua build gaming da sogno.', 'rogstrixb550.png', 200, 'Asus', 6, 11, 1, 'AMD'),
(51, 'X570 Aorus Ultra', 'Marca:‎Gigabyte: Chipset:AMD: Serie:X570 AORUS ULTRA: Dimensioni prodotto:‎30.5 x 24.4 x 4 cm: Numero modello Articolo:‎X570 AORUS ULTRA: Fattore di forma:‎ATX: Supporto processore:‎Socket AM4: Tecnologia di memoria:	‎DDR4: Tipologia di memoria computer	‎:DDR4 SDRAM: Clock di Memoria:‎3600 MHz: Interfaccia scheda grafica:‎PCI-E: Tipo wireless:‎802.11a/b/g/n: Numero di porte USB 2.0:‎4: Peso Articolo:‎1.7 kg', 'Per creare un\'esperienza VR perfetta, le schede madri GIGABYTE offrono le ottimi funzionalità per rendere la realtà virtuale simile alla tua realtà attuale. Per creare un\'ottima atmosfera, le schede madri GIGABYTE includono RGB Fusion per metterti al centro dell\'azione.', 'x570aorus.png', 320, 'Gigabyte', 6, 1, 1, 'AMD'),
(52, 'X570 Gaming Plus', 'Marca:‎MSI: Chipset:AMD: Serie:X570 GAMING PLUS: Colore:‎Nero: Dimensioni prodotto:‎34.6 x 26.9 x 6.5 cm: Numero modello Articolo:‎911-7C37-040: Marchio processore:‎AMD: Supporto processore:Socket AM4: Tecnologia di memoria:‎DDR4: Tipologia di memoria computer	:‎DDR4 SDRAM: Dimensioni massima memoria RAM:‎64 GB: Clock di Memoria:‎4800 MHz: Interfaccia scheda grafica:PCI-E: Numero di porte USB 2.0:‎2: Peso Articolo:1.1 kg', 'Goditi l\'esperienza della nuova generazione di schede madri AMD con la MPG X570 GAMING PRO CARBON WIFI in grado di portare i processori di terza generazione AMD 3000 Series AM4 al massimo. Sorpassa i limiti del tuo sistema con Lightning Gen 4 e Wi-Fi 6 AX. Strumenti smart come DDR4 Boost e Core Boost, creati per mantenere le tue performance sempre al top. il Dissipatore FROZR è stato progettato con un sistema di AI tuning al fine di mantenere il tuo PC fresco. silenzioso ed efficiente.', 'x570gaming.png', 180, 'MSI', 6, 9, 1, 'AMD'),
(53, 'X570-I Aorus', 'Marca:Gigabyte: Chipset:AMD: Modello:X570 I AORUS PRO WIFI: Nome modello:X570 I AORUS PRO WIFI: Dimensioni prodotto:‎26.49 x 23.5 x 7.98 cm: Numero modello Articolo:‎X570 I AORUS PRO WIFI: Anno modello:‎2018: Numero Articolo:‎X570 I AORUS PRO WIFI: Capacità di memoria:‎64 GB: Tecnologia di memoria:‎DDR4: Dimensioni memoria RAM installata:‎64 GB: Dimensioni massima memoria RAM:‎64 GB: Tecnologia memoria RAM:‎DDR4: Tipologia di memoria computer:‎DDR4 SDRAM: Supporto processore:‎Socket AM4: Processori compatibili:AMD 3rd Generation Ryzen, AMD 2nd Gerenration Ryzen: Numero modello processore:SOCKET AM4 RYZEN PROCESSORS: Interfaccia scheda grafica:PCI-E: Tipo di chip:‎AMD 570X: Wattaggio:125 watt: Tipo wireless:‎Bluetooth: Fattore di forma:Mini ITX: Peso Articolo:‎998 g', 'Supporta AMD Ryzen di terza generazione / Ryzen di 2a generazione con processori grafici Radeon Vega Dual Channel ECC/Non ECC Unbuffered DDR4, 2 DIMM diretta 8 fasi Infineon soluzione VRM digitale con 70a power stage esteso VRM e 5W/MK pad termico Dual Ultra-Fast NVMe PCIe 4.0/3.0 x4 M.2 Intel Wi-Fi 6 802.11ax e BT 5 con un\'antenna o noi Amp Up audio con ALC1220 VB Intel Gigabit LAN turbocompressore USB per dispositivo mobile Supporto ricarica rapida RGB Fusion con luce LED indirizzabile Multi Zone Mostra design Smart Fan 5 Hybrid Fan Headers con FAN STOP e rilevamento del rumore posteriore USB 3.2 Gen 2 Tipo C integrato I/O scudo Q Flash Plus aggiornamento OS senza installare CPU, memoria, GPU.', 'x570iaorus.png', 300, 'Gigabyte', 6, 1, 1, 'AMD'),
(54, 'TRX40 Taichi', 'Marca:Asrock: Chipset:AMD: Serie:‎Trx40: Dimensioni prodotto:‎36.83 x 31.75 x 15.24 cm; 1.5 Kg: Numero modello Articolo:‎TRX40 TAICHI: Supporto processore:‎STRX4: Tecnologia di memoria:	‎DDR4: Tipologia di memoria computer	‎:DDR4 SDRAM: Memoria massima supportata:‎256 GB: Clock di Memoria:‎2666 MHz: Interfaccia scheda grafica:‎PCI-E: Tipo wireless:‎802.11ax: Wattaggio:‎125 watt: Peso Articolo:‎1.5 kg', 'A differenza dei tradizionali connettori di alimentazione per CPU dual-core che si trovano strettamente sullo stesso lato, ASRock li separa da entrambi i lati della scheda madre per creare una corsia più ampia per la CPU VRM. Questo design offre una migliore efficienza di uscita delle prestazioni e una temperatura più bassa, migliorando la stabilità del sistema e aumentando il potenziale di overclocking.', 'trx40taichi.png', 620, 'ASRock', 6, 10, 1, 'AMD');

--
-- Dump dei dati per la tabella `categoria`
--

INSERT INTO `categoria` (`ID_Categoria`, `nome`, `nome_esposizione`, `descrizione`) VALUES
(1, 'Motherboard', 'Schede madri', 'scegli tra la vasta gamma di schede madri quella che più fa al caso tuo e del tuo computer'),
(2, 'GPU', 'Schede Video', ' sfrutta la potenza delle nostre nuove schede video per avere un gioco fluido e senza cali di frame'),
(3, 'PSU', 'Alimentatori', ' scegli il prodotto che più soddisfa le tue esigenze tra una vasta scelta di alimentatori modulari e non modulari'),
(4, 'RAM', 'RAM', 'scegli la tua RAM tra i migliori Kit disponibili, sia da 32 GB che da 16 GB e con funzionalita RGB'),
(5, 'CPU', 'Processori', ' il cuore del tuo computer, scegli tra i nostri processori quello che ti permetterà una prestazione elevata senza interruzioni'),
(6, 'Case', 'Case', ' mostra a tutti il tuo computer con i nostri case stravaganti con vetro trasparente, illuminazione rgb e un\'ottima areanzione'),
(7, 'Cooler', 'Dissipatori', ' i migliori dissipatori sul mercato sia liquidi che a ventola, mantieni temperature basse e fps alti grazie ai nostri prodotti ');

--
-- Dump dei dati per la tabella `utente`
--

INSERT INTO `utente` (`ID_Utente`, `nome`, `username`, `password`, `Tipo`) VALUES
(1, 'Gigabyte', 'gigabyte@venditore.com', 'gigabyte2022', 'venditore'),
(2, 'AMD', 'amd@venditore.com', 'amd2022', 'venditore'),
(3, 'Intel', 'intel@venditore.com', 'intel2022', 'venditore'),
(4, 'Corsair', 'corsair@venditore.com', 'corsair2022', 'venditore'),
(5, 'Crucial', 'crucial@venditore.com', 'crucial2022', 'venditore'),
(6, 'Cooler Master', 'coolermaster@venditore.com', 'coolermaster2022', 'venditore'),
(7, 'Noctua', 'noctua@venditore.com', 'noctua2022', 'venditore'),
(8, 'Thermaltake', 'thermaltake@venditore.com', 'thermaltake2022', 'venditore'),
(9, 'MSI', 'msi@venditore.com', 'msi2022', 'venditore'),
(10, 'ASRock', 'asrock@venditore.com', 'asrock2022', 'venditore'),
(11, 'Asus', 'asus@venditore.com', 'asus2022', 'venditore'),
(12, 'Luis', 'luisinca@gmail.com', '1234', 'cliente');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
